import { ConceptTemplate } from "./types";

/**
 * 동아리 2학년 학생 대상 파이썬 개념 템플릿.
 * 자료(노션/코랩 복사 텍스트)에서 keywords 중 하나라도 발견되면
 * 해당 개념이 목록에 포함된다. (lib/extractConcepts.ts 참고)
 */
export const CONCEPT_TEMPLATES: ConceptTemplate[] = [
  {
    id: "variables",
    title: "변수와 자료형",
    keywords: ["변수", "자료형", "type(", "int(", "float(", "str(", "bool("],
    defaultExplanation:
      "변수는 데이터를 저장하는 이름표입니다. 파이썬은 int(정수), float(실수), str(문자열), bool(참/거짓) 같은 자료형을 자동으로 판단해요. type() 함수로 자료형을 확인할 수 있습니다.",
    questionBank: {
      하: [
        {
          id: "variables-하-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 10\nprint(type(x))`,
          options: ["<class 'int'>", "<class 'str'>", "<class 'float'>", "<class 'bool'>"],
          answerIndex: 0,
        },
        {
          id: "variables-하-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = "5"\ny = 3\nprint(x + str(y))`,
          options: ["53", "8", "5 3", "오류"],
          answerIndex: 0,
        },
        {
          id: "variables-하-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `a = 3\nb = 2\nprint(a / b)`,
          options: ["1.5", "1", "1.0", "오류"],
          answerIndex: 0,
        },
        {
          id: "variables-하-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `name = "Python"\nprint(len(name))`,
          options: ["6", "5", "7", "오류"],
          answerIndex: 0,
        },
        {
          id: "variables-하-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 7\nprint(x % 2)`,
          options: ["1", "0", "3", "3.5"],
          answerIndex: 0,
        },
      ],
      중: [
        {
          id: "variables-중-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `a = 5\nb = "5"\nprint(a == b)`,
          options: ["False", "True", "오류", "None"],
          answerIndex: 0,
        },
        {
          id: "variables-중-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 10\nx += 5\nx *= 2\nprint(x)`,
          options: ["30", "15", "20", "25"],
          answerIndex: 0,
        },
        {
          id: "variables-중-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `print(int("3.7"))`,
          options: ["오류(ValueError)", "3", "4", "3.7"],
          answerIndex: 0,
        },
        {
          id: "variables-중-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = True\ny = 1\nprint(x == y)`,
          options: ["True", "False", "오류", "None"],
          answerIndex: 0,
        },
        {
          id: "variables-중-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `print(3 // 2 + 3 % 2)`,
          options: ["2", "1", "3", "1.5"],
          answerIndex: 0,
        },
      ],
      상: [
        {
          id: "variables-상-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 0.1 + 0.2\nprint(x == 0.3)`,
          options: ["False", "True", "오류", "None"],
          answerIndex: 0,
        },
        {
          id: "variables-상-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `a = "10"\nb = "3"\nprint(int(a) // int(b), a + b)`,
          options: ["3 103", "3.33 103", "103 3", "오류"],
          answerIndex: 0,
        },
        {
          id: "variables-상-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 5\nprint(str(x) * 3)`,
          options: ["555", "15", "5 5 5", "오류"],
          answerIndex: 0,
        },
        {
          id: "variables-상-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `print(bool(""), bool("0"), bool(0))`,
          options: ["False True False", "True True True", "False False False", "True False False"],
          answerIndex: 0,
        },
        {
          id: "variables-상-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = None\nprint(x == None, x is None)`,
          options: ["True True", "False False", "True False", "오류"],
          answerIndex: 0,
        },
      ],
    },
  },
  {
    id: "conditional",
    title: "조건문 (if)",
    keywords: ["조건문", "if ", "elif", "else:", "조건"],
    defaultExplanation:
      "조건문(if/elif/else)은 조건이 참인지 거짓인지에 따라 다른 코드를 실행합니다. 비교 연산자(==, >, < 등)와 논리 연산자(and, or, not)를 함께 사용해 다양한 조건을 만들 수 있어요.",
    questionBank: {
      하: [
        {
          id: "conditional-하-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 7\nif x > 5:\n    print("A")\nelse:\n    print("B")`,
          options: ["A", "B", "AB", "오류"],
          answerIndex: 0,
        },
        {
          id: "conditional-하-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 3\nif x == 3:\n    print("같음")`,
          options: ["같음", "(아무것도 출력 안 됨)", "오류", "False"],
          answerIndex: 0,
        },
        {
          id: "conditional-하-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = -2\nif x > 0:\n    print("양수")\nelif x < 0:\n    print("음수")\nelse:\n    print("0")`,
          options: ["음수", "양수", "0", "오류"],
          answerIndex: 0,
        },
        {
          id: "conditional-하-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 10\nif x % 2 == 0:\n    print("짝수")\nelse:\n    print("홀수")`,
          options: ["짝수", "홀수", "10", "오류"],
          answerIndex: 0,
        },
        {
          id: "conditional-하-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 5\nif x:\n    print("참")\nelse:\n    print("거짓")`,
          options: ["참", "거짓", "5", "오류"],
          answerIndex: 0,
        },
      ],
      중: [
        {
          id: "conditional-중-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 15\nif x > 20:\n    print("큼")\nelif x > 10:\n    print("중간")\nelif x > 5:\n    print("작음")\nelse:\n    print("아주작음")`,
          options: ["중간", "큼", "작음", "아주작음"],
          answerIndex: 0,
        },
        {
          id: "conditional-중-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 4\ny = 9\nif x > 3 and y > 10:\n    print("A")\nelif x > 3 or y > 10:\n    print("B")\nelse:\n    print("C")`,
          options: ["B", "A", "C", "오류"],
          answerIndex: 0,
        },
        {
          id: "conditional-중-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 0\nif x:\n    print("참")\nelif not x:\n    print("거짓이라 not")\nelse:\n    print("기타")`,
          options: ["거짓이라 not", "참", "기타", "오류"],
          answerIndex: 0,
        },
        {
          id: "conditional-중-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `score = 85\nif score >= 90:\n    grade = "A"\nelif score >= 80:\n    grade = "B"\nelif score >= 70:\n    grade = "C"\nelse:\n    grade = "F"\nprint(grade)`,
          options: ["B", "A", "C", "F"],
          answerIndex: 0,
        },
        {
          id: "conditional-중-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 5\nif x == 5:\n    if x > 0:\n        print("양의 5")\n    else:\n        print("음의 5")`,
          options: ["양의 5", "음의 5", "5", "오류"],
          answerIndex: 0,
        },
      ],
      상: [
        {
          id: "conditional-상-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 7\nresult = "짝수" if x % 2 == 0 else "홀수"\nprint(result)`,
          options: ["홀수", "짝수", "7", "오류"],
          answerIndex: 0,
        },
        {
          id: "conditional-상-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `a, b, c = 3, 5, 4\nif a > b and a > c:\n    print("a")\nelif b > a and b > c:\n    print("b")\nelse:\n    print("c")`,
          options: ["b", "a", "c", "오류"],
          answerIndex: 0,
        },
        {
          id: "conditional-상-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 10\nif x > 5:\n    pass\nelse:\n    print("작음")\nprint("끝")`,
          options: ["끝", "작음, 끝", "작음", "오류"],
          answerIndex: 0,
        },
        {
          id: "conditional-상-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = "5"\nif x == 5:\n    print("같음")\nelse:\n    print("다름")`,
          options: ["다름", "같음", "오류", "None"],
          answerIndex: 0,
        },
        {
          id: "conditional-상-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 3\nif 1 < x < 5:\n    print("범위 안")\nelse:\n    print("범위 밖")`,
          options: ["범위 안", "범위 밖", "오류", "True"],
          answerIndex: 0,
        },
      ],
    },
  },
  {
    id: "loop",
    title: "반복문 (for/while)",
    keywords: ["반복문", "for ", "while ", "range(", "반복"],
    defaultExplanation:
      "반복문(for, while)은 같은 코드를 여러 번 실행할 때 사용합니다. for는 정해진 범위나 리스트를 순회하고, while은 조건이 참인 동안 반복해요. break로 중단하고 continue로 다음 반복으로 건너뛸 수 있습니다.",
    questionBank: {
      하: [
        {
          id: "loop-하-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `for i in range(5):\n    print(i)`,
          options: ["0~4", "1~5", "0~5", "오류"],
          answerIndex: 0,
        },
        {
          id: "loop-하-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `total = 0\nfor i in range(1, 4):\n    total += i\nprint(total)`,
          options: ["6", "3", "10", "오류"],
          answerIndex: 0,
        },
        {
          id: "loop-하-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `i = 0\nwhile i < 3:\n    print(i)\n    i += 1`,
          options: ["0 1 2", "1 2 3", "0 1 2 3", "오류(무한루프)"],
          answerIndex: 0,
        },
        {
          id: "loop-하-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `for word in ["a", "b", "c"]:\n    print(word)`,
          options: ["a b c", "['a', 'b', 'c']", "abc", "오류"],
          answerIndex: 0,
        },
        {
          id: "loop-하-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `for i in range(2, 10, 3):\n    print(i)`,
          options: ["2 5 8", "2 3 4", "2 4 6 8", "오류"],
          answerIndex: 0,
        },
      ],
      중: [
        {
          id: "loop-중-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `count = 0\nfor i in range(10):\n    if i % 2 == 0:\n        count += 1\nprint(count)`,
          options: ["5", "4", "10", "0"],
          answerIndex: 0,
        },
        {
          id: "loop-중-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `n = 5\nresult = 1\nfor i in range(1, n + 1):\n    result *= i\nprint(result)`,
          options: ["120", "24", "20", "15"],
          answerIndex: 0,
        },
        {
          id: "loop-중-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `i = 0\nwhile i < 5:\n    i += 1\n    if i == 3:\n        continue\n    print(i)`,
          options: ["1 2 4 5", "1 2 3 4 5", "1 2 4", "오류"],
          answerIndex: 0,
        },
        {
          id: "loop-중-4",
          prompt: "print()는 총 몇 번 실행될까?",
          code: `for i in range(3):\n    for j in range(2):\n        print(i, j)`,
          options: ["6번", "3번", "2번", "5번"],
          answerIndex: 0,
        },
        {
          id: "loop-중-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `nums = [1, 2, 3, 4, 5]\ntotal = 0\nfor n in nums:\n    if n > 3:\n        break\n    total += n\nprint(total)`,
          options: ["6", "10", "4", "15"],
          answerIndex: 0,
        },
      ],
      상: [
        {
          id: "loop-상-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `result = [i * i for i in range(5) if i % 2 == 0]\nprint(result)`,
          options: ["[0, 4, 16]", "[0, 1, 4, 9, 16]", "[0, 2, 4]", "오류"],
          answerIndex: 0,
        },
        {
          id: "loop-상-2",
          prompt: "print()는 총 몇 번 실행될까?",
          code: `for i in range(3):\n    for j in range(3):\n        if j == 1:\n            break\n        print(i, j)`,
          options: ["3번", "9번", "6번", "0번"],
          answerIndex: 0,
        },
        {
          id: "loop-상-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `total = 0\ni = 1\nwhile True:\n    if i > 5:\n        break\n    total += i\n    i += 1\nprint(total)`,
          options: ["15", "10", "5", "오류(무한루프)"],
          answerIndex: 0,
        },
        {
          id: "loop-상-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `nums = [3, 1, 4, 1, 5]\nmax_val = nums[0]\nfor n in nums:\n    if n > max_val:\n        max_val = n\nprint(max_val)`,
          options: ["5", "4", "3", "1"],
          answerIndex: 0,
        },
        {
          id: "loop-상-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `for i in range(5):\n    if i == 2:\n        continue\n    elif i == 4:\n        break\n    print(i)`,
          options: ["0 1 3", "0 1 2 3", "0 1 3 4", "오류"],
          answerIndex: 0,
        },
      ],
    },
  },
  {
    id: "list",
    title: "리스트",
    keywords: ["리스트", ".append(", "list(", ".remove(", ".sort("],
    defaultExplanation:
      "리스트는 여러 값을 순서대로 담는 자료구조입니다. 대괄호 []로 만들고, append()로 추가, remove()로 삭제, 인덱스([0], [-1])로 값을 꺼낼 수 있어요.",
    questionBank: {
      하: [
        {
          id: "list-하-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `nums = [1, 2, 3]\nnums.append(4)\nprint(nums)`,
          options: ["[1, 2, 3, 4]", "[4, 1, 2, 3]", "[1, 2, 3]", "오류"],
          answerIndex: 0,
        },
        {
          id: "list-하-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `fruits = ["사과", "바나나", "포도"]\nprint(fruits[1])`,
          options: ["바나나", "사과", "포도", "오류"],
          answerIndex: 0,
        },
        {
          id: "list-하-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `nums = [1, 2, 3, 4, 5]\nprint(len(nums))`,
          options: ["5", "4", "6", "오류"],
          answerIndex: 0,
        },
        {
          id: "list-하-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `nums = [10, 20, 30]\nprint(nums[-1])`,
          options: ["30", "10", "20", "오류"],
          answerIndex: 0,
        },
        {
          id: "list-하-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `a = [1, 2]\nb = [3, 4]\nprint(a + b)`,
          options: ["[1, 2, 3, 4]", "[4, 6]", "[1, 2, 3, 4, 5]", "오류"],
          answerIndex: 0,
        },
      ],
      중: [
        {
          id: "list-중-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `nums = [1, 2, 3, 4, 5]\nprint(nums[1:3])`,
          options: ["[2, 3]", "[1, 2, 3]", "[2, 3, 4]", "오류"],
          answerIndex: 0,
        },
        {
          id: "list-중-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `nums = [1, 2, 3]\nnums.remove(2)\nprint(nums)`,
          options: ["[1, 3]", "[1, 2]", "[2, 3]", "오류"],
          answerIndex: 0,
        },
        {
          id: "list-중-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `nums = [3, 1, 2]\nnums.sort()\nprint(nums)`,
          options: ["[1, 2, 3]", "[3, 1, 2]", "[3, 2, 1]", "오류"],
          answerIndex: 0,
        },
        {
          id: "list-중-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `nums = [1, 2, 3]\nfor i in range(len(nums)):\n    nums[i] *= 2\nprint(nums)`,
          options: ["[2, 4, 6]", "[1, 2, 3]", "[2, 2, 2]", "오류"],
          answerIndex: 0,
        },
        {
          id: "list-중-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `nums = [1, 2, 3]\nprint(3 in nums, 5 in nums)`,
          options: ["True False", "False True", "True True", "오류"],
          answerIndex: 0,
        },
      ],
      상: [
        {
          id: "list-상-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `matrix = [[1, 2], [3, 4]]\nprint(matrix[1][0])`,
          options: ["3", "1", "2", "4"],
          answerIndex: 0,
        },
        {
          id: "list-상-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `nums = [1, 2, 3]\nnums2 = nums\nnums2.append(4)\nprint(nums)`,
          options: ["[1, 2, 3, 4]", "[1, 2, 3]", "오류", "[4]"],
          answerIndex: 0,
        },
        {
          id: "list-상-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `nums = [i for i in range(10) if i % 3 == 0]\nprint(nums)`,
          options: ["[0, 3, 6, 9]", "[0, 3, 6, 9, 12]", "[3, 6, 9]", "오류"],
          answerIndex: 0,
        },
        {
          id: "list-상-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `a = [1, 2, 3]\nb = a[:]\nb.append(4)\nprint(a, b)`,
          options: [
            "[1, 2, 3] [1, 2, 3, 4]",
            "[1, 2, 3, 4] [1, 2, 3, 4]",
            "[1, 2, 3] [1, 2, 3]",
            "오류",
          ],
          answerIndex: 0,
        },
        {
          id: "list-상-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `nums = [5, 3, 8, 1]\nprint(sorted(nums, reverse=True))`,
          options: ["[8, 5, 3, 1]", "[1, 3, 5, 8]", "[5, 3, 8, 1]", "오류"],
          answerIndex: 0,
        },
      ],
    },
  },
  {
    id: "dict",
    title: "딕셔너리",
    keywords: ["딕셔너리", "dict(", ".get(", ".items(", ".keys("],
    defaultExplanation:
      "딕셔너리는 키(key)와 값(value)을 짝지어 저장하는 자료구조입니다. {키: 값} 형태로 만들고, get()으로 안전하게 값을 꺼내거나 items()로 모든 키-값 쌍을 순회할 수 있어요.",
    questionBank: {
      하: [
        {
          id: "dict-하-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `person = {"이름": "지민", "나이": 15}\nprint(person["이름"])`,
          options: ["지민", "나이", "15", "오류"],
          answerIndex: 0,
        },
        {
          id: "dict-하-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `d = {"a": 1, "b": 2}\nd["c"] = 3\nprint(d)`,
          options: ["{'a': 1, 'b': 2, 'c': 3}", "{'a': 1, 'b': 2}", "{'c': 3}", "오류"],
          answerIndex: 0,
        },
        {
          id: "dict-하-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `d = {"x": 10}\nprint(len(d))`,
          options: ["1", "0", "10", "오류"],
          answerIndex: 0,
        },
        {
          id: "dict-하-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `d = {"a": 1, "b": 2}\nprint(list(d.keys()))`,
          options: ["['a', 'b']", "['1', '2']", "[1, 2]", "오류"],
          answerIndex: 0,
        },
        {
          id: "dict-하-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `d = {"a": 1}\nprint("a" in d, "b" in d)`,
          options: ["True False", "False True", "True True", "오류"],
          answerIndex: 0,
        },
      ],
      중: [
        {
          id: "dict-중-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `d = {"a": 1, "b": 2}\nprint(d.get("c", 0))`,
          options: ["0", "오류(KeyError)", "None", "c"],
          answerIndex: 0,
        },
        {
          id: "dict-중-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `d = {"a": 1, "b": 2}\ndel d["a"]\nprint(d)`,
          options: ["{'b': 2}", "{'a': 1}", "{}", "오류"],
          answerIndex: 0,
        },
        {
          id: "dict-중-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `d = {"a": 1, "b": 2}\nfor key in d:\n    print(key)`,
          options: ["a b", "1 2", "a: 1 b: 2", "오류"],
          answerIndex: 0,
        },
        {
          id: "dict-중-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `d = {"a": 1, "b": 2}\nfor k, v in d.items():\n    print(k, v)`,
          options: ["a 1 b 2", "a b", "1 2", "오류"],
          answerIndex: 0,
        },
        {
          id: "dict-중-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `scores = {"철수": 90, "영희": 85}\nscores["철수"] = 95\nprint(scores["철수"])`,
          options: ["95", "90", "오류", "None"],
          answerIndex: 0,
        },
      ],
      상: [
        {
          id: "dict-상-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `d = {}\nfor i in range(3):\n    d[i] = i * i\nprint(d)`,
          options: ["{0: 0, 1: 1, 2: 4}", "{0: 0, 1: 2, 2: 4}", "{1: 1, 2: 4, 3: 9}", "오류"],
          answerIndex: 0,
        },
        {
          id: "dict-상-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `d = {"a": [1, 2], "b": [3, 4]}\nd["a"].append(5)\nprint(d["a"])`,
          options: ["[1, 2, 5]", "[1, 2]", "[5]", "오류"],
          answerIndex: 0,
        },
        {
          id: "dict-상-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `words = ["a", "b", "a", "c", "b", "a"]\ncount = {}\nfor w in words:\n    count[w] = count.get(w, 0) + 1\nprint(count["a"])`,
          options: ["3", "2", "1", "오류"],
          answerIndex: 0,
        },
        {
          id: "dict-상-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `d1 = {"a": 1}\nd2 = {"b": 2}\nd1.update(d2)\nprint(d1)`,
          options: ["{'a': 1, 'b': 2}", "{'a': 1}", "{'b': 2}", "오류"],
          answerIndex: 0,
        },
        {
          id: "dict-상-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `d = {"a": 1, "b": 2, "c": 3}\nprint(max(d, key=d.get))`,
          options: ["c", "a", "3", "b"],
          answerIndex: 0,
        },
      ],
    },
  },
  {
    id: "function",
    title: "함수",
    keywords: ["함수", "def ", "return ", "function"],
    defaultExplanation:
      "함수는 반복해서 쓰는 코드를 묶어 이름을 붙인 것입니다. def로 정의하고, 매개변수로 값을 받아 return으로 결과를 돌려줘요. 기본값 매개변수나 *args 같은 문법도 있습니다.",
    questionBank: {
      하: [
        {
          id: "function-하-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `def greet():\n    print("안녕")\n\ngreet()`,
          options: ["안녕", "greet", "오류", "(아무것도 출력 안 됨)"],
          answerIndex: 0,
        },
        {
          id: "function-하-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `def add(a, b):\n    return a + b\n\nprint(add(2, 3))`,
          options: ["5", "23", "오류", "None"],
          answerIndex: 0,
        },
        {
          id: "function-하-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `def square(x):\n    return x * x\n\nprint(square(4))`,
          options: ["16", "8", "4", "오류"],
          answerIndex: 0,
        },
        {
          id: "function-하-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `def say_hi(name):\n    print("안녕, " + name)\n\nsay_hi("민수")`,
          options: ["안녕, 민수", "민수", "안녕", "오류"],
          answerIndex: 0,
        },
        {
          id: "function-하-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `def no_return():\n    x = 1 + 1\n\nprint(no_return())`,
          options: ["None", "2", "오류", "(아무것도 출력 안 됨)"],
          answerIndex: 0,
        },
      ],
      중: [
        {
          id: "function-중-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `def add(a, b=10):\n    return a + b\n\nprint(add(5))`,
          options: ["15", "5", "10", "오류"],
          answerIndex: 0,
        },
        {
          id: "function-중-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `def total(*nums):\n    return sum(nums)\n\nprint(total(1, 2, 3))`,
          options: ["6", "3", "(1, 2, 3)", "오류"],
          answerIndex: 0,
        },
        {
          id: "function-중-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `x = 5\ndef change():\n    x = 10\n    return x\n\nprint(change(), x)`,
          options: ["10 5", "10 10", "5 5", "오류"],
          answerIndex: 0,
        },
        {
          id: "function-중-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `def is_even(n):\n    return n % 2 == 0\n\nprint(is_even(7))`,
          options: ["False", "True", "7", "오류"],
          answerIndex: 0,
        },
        {
          id: "function-중-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `def greet(name="친구"):\n    return f"안녕, {name}"\n\nprint(greet())`,
          options: ["안녕, 친구", "안녕, {name}", "오류", "None"],
          answerIndex: 0,
        },
      ],
      상: [
        {
          id: "function-상-1",
          prompt: "아래 코드의 실행 결과는?",
          code: `def outer():\n    x = 1\n    def inner():\n        return x + 1\n    return inner()\n\nprint(outer())`,
          options: ["2", "1", "오류", "None"],
          answerIndex: 0,
        },
        {
          id: "function-상-2",
          prompt: "아래 코드의 실행 결과는?",
          code: `def fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)\n\nprint(fact(4))`,
          options: ["24", "12", "4", "오류"],
          answerIndex: 0,
        },
        {
          id: "function-상-3",
          prompt: "아래 코드의 실행 결과는?",
          code: `def modify(lst):\n    lst.append(100)\n\nnums = [1, 2, 3]\nmodify(nums)\nprint(nums)`,
          options: ["[1, 2, 3, 100]", "[1, 2, 3]", "[100]", "오류"],
          answerIndex: 0,
        },
        {
          id: "function-상-4",
          prompt: "아래 코드의 실행 결과는?",
          code: `def calc(a, b, op="+"):\n    if op == "+":\n        return a + b\n    elif op == "*":\n        return a * b\n\nprint(calc(3, 4, op="*"))`,
          options: ["12", "7", "오류", "None"],
          answerIndex: 0,
        },
        {
          id: "function-상-5",
          prompt: "아래 코드의 실행 결과는?",
          code: `counter = 0\ndef increase():\n    global counter\n    counter += 1\n\nincrease()\nincrease()\nprint(counter)`,
          options: ["2", "0", "1", "오류"],
          answerIndex: 0,
        },
      ],
    },
  },
];
